import { timestamp, uuid } from "drizzle-orm/pg-core";

/**
 * Columns shared by every table: UUID primary key generated by the database and
 * UTC timestamps. `updated_at` is refreshed by the application (Drizzle `$onUpdate`),
 * not by a database trigger.
 *
 * Exposed as a factory so that every table gets its own column builders.
 */
export function baseColumns() {
  return {
    id: uuid("id").primaryKey().defaultRandom(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  };
}
