import { fileURLToPath } from "node:url";

import { drizzle } from "drizzle-orm/postgres-js";
import { migrate } from "drizzle-orm/postgres-js/migrator";
import postgres from "postgres";

import { seedModules } from "./seed";

/** Folder with the SQL migrations generated by `npm run db:generate`. */
export const MIGRATIONS_FOLDER = fileURLToPath(new URL("../../drizzle", import.meta.url));

/** Suffix every test database name must have (`vistato_test`, `vistato_migrate_<random>_test`). */
export const TEST_DATABASE_SUFFIX = "_test";

/**
 * Database name a postgres.js connection URL connects to, resolved like postgres.js does:
 * the path without the leading slash (not URL-decoded), possibly overridden by a
 * `database` query parameter, which is sent as a startup parameter. Multi-host URLs
 * (`host1,host2`) are supported. Returns "" when the URL names no database: postgres.js
 * would then fall back to PGDATABASE or the user name.
 */
export function databaseNameFromUrl(url: string): string {
  const afterScheme = url.indexOf("://");
  if (afterScheme < 0) throw new Error("Invalid database URL: missing scheme.");
  // Same host handling as postgres.js: keep only the first host of a multi-host URL.
  const authority = url.slice(afterScheme + 3).split(/[?/]/)[0];
  const host = authority.slice(authority.lastIndexOf("@") + 1);
  let parsed: URL;
  try {
    parsed = new URL(url.replace(host, host.split(",")[0]));
  } catch {
    throw new Error("Invalid database URL.");
  }
  const fromQuery = parsed.searchParams.getAll("database");
  if (fromQuery.length > 0) return fromQuery[fromQuery.length - 1];
  return parsed.pathname.slice(1);
}

/**
 * Throws unless `url` points to a database whose name ends with `_test`, so that test
 * tooling (migrations, seed, TRUNCATE between tests) can never hit the development or
 * production database by mistake. Returns the database name.
 */
export function assertTestDatabase(url: string): string {
  const name = databaseNameFromUrl(url);
  if (!name.endsWith(TEST_DATABASE_SUFFIX) || name === TEST_DATABASE_SUFFIX) {
    throw new Error(
      `Refusing to use database "${name}" for tests: its name must end with "${TEST_DATABASE_SUFFIX}".`,
    );
  }
  return name;
}

/**
 * Returns the test database URL, or throws when it is missing or does not point to a
 * `*_test` database. Scripts that act on the test database must never fall back to
 * DATABASE_URL (the development database).
 */
export function requireTestDatabaseUrl(env: Record<string, string | undefined> = process.env): string {
  const url = env.TEST_DATABASE_URL?.trim();
  if (!url) {
    throw new Error("TEST_DATABASE_URL is not set (see .env.example): refusing to run.");
  }
  assertTestDatabase(url);
  return url;
}

/**
 * Server-side counterpart of `assertTestDatabase`: asks Postgres which database the
 * connection is actually using, independently of how the URL was parsed.
 */
export async function assertConnectedToTestDatabase(sql: postgres.Sql): Promise<void> {
  const [{ name }] = await sql<{ name: string }[]>`select current_database() as name`;
  if (!name.endsWith(TEST_DATABASE_SUFFIX) || name === TEST_DATABASE_SUFFIX) {
    throw new Error(
      `Refusing to use database "${name}" for tests: its name must end with "${TEST_DATABASE_SUFFIX}".`,
    );
  }
}

export interface DatabaseTaskOptions {
  /** Refuse to act unless the URL and the connected database are a `*_test` database. */
  testOnly?: boolean;
}

async function withDatabase<T>(
  url: string,
  options: DatabaseTaskOptions,
  fn: (db: ReturnType<typeof drizzle>) => Promise<T>,
): Promise<T> {
  if (options.testOnly) assertTestDatabase(url);
  const sql = postgres(url, { max: 1, onnotice: () => {} });
  try {
    if (options.testOnly) await assertConnectedToTestDatabase(sql);
    return await fn(drizzle(sql));
  } finally {
    await sql.end();
  }
}

/** Applies every pending migration in `drizzle/` to the database at `url`. */
export function migrateDatabase(url: string, options: DatabaseTaskOptions = {}): Promise<void> {
  return withDatabase(url, options, (db) => migrate(db, { migrationsFolder: MIGRATIONS_FOLDER }));
}

/** Writes the module catalogue to the database at `url` (idempotent). */
export function seedDatabase(url: string, options: DatabaseTaskOptions = {}): Promise<void> {
  return withDatabase(url, options, (db) => seedModules(db));
}
