import { fileURLToPath } from "node:url";

import { drizzle } from "drizzle-orm/postgres-js";
import { migrate } from "drizzle-orm/postgres-js/migrator";
import postgres from "postgres";

import { seedModules } from "./seed";

/** Folder with the SQL migrations generated by `npm run db:generate`. */
export const MIGRATIONS_FOLDER = fileURLToPath(new URL("../../drizzle", import.meta.url));

/**
 * Returns the test database URL, or throws when it is missing. Scripts that act on
 * the test database must never fall back to DATABASE_URL (the development database).
 */
export function requireTestDatabaseUrl(env: Record<string, string | undefined> = process.env): string {
  const url = env.TEST_DATABASE_URL?.trim();
  if (!url) {
    throw new Error("TEST_DATABASE_URL is not set (see .env.example): refusing to run.");
  }
  return url;
}

async function withDatabase<T>(
  url: string,
  fn: (db: ReturnType<typeof drizzle>) => Promise<T>,
): Promise<T> {
  const sql = postgres(url, { max: 1, onnotice: () => {} });
  try {
    return await fn(drizzle(sql));
  } finally {
    await sql.end();
  }
}

/** Applies every pending migration in `drizzle/` to the database at `url`. */
export function migrateDatabase(url: string): Promise<void> {
  return withDatabase(url, (db) => migrate(db, { migrationsFolder: MIGRATIONS_FOLDER }));
}

/** Writes the module catalogue to the database at `url` (idempotent). */
export function seedDatabase(url: string): Promise<void> {
  return withDatabase(url, (db) => seedModules(db));
}
