/**
 * Database schema (Drizzle ORM).
 *
 * Intentionally empty: the domain model (tenants, users, modules, entitlements,
 * invoices, approval flows...) is introduced ticket by ticket, each with its own
 * migration generated by `npm run db:generate`.
 */
export {};
